
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AppSessionProvider} from "@/app/_providers/app-session-provider";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Next Auth App",
    description: "Generated by create next app",
    openGraph: {
        title: 'Next Auth App',
        description: 'Welcome to the home page of Your App.',
        images: ['/path-to-image.jpg'],
        url: 'https://my-app.com',
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AppSessionProvider>
            <Header/>
            {children}
            <Footer/>
        </AppSessionProvider>
        </body>
        </html>
    );
}
